import { Router } from "express";
import bicycleRoutes from "../modules/bicycles/bicycle.routes.js";
import brandRoutes from "../modules/brands/brand.routes.js";
import bicycleDetailRoutes from "../modules/bicycle-details/bicycle-detail.routes.js";
import customerRoutes from "../modules/customers/customer.routes.js";
import orderRoutes from "../modules/orders/order.routes.js";
const router = Router();
router.use("/bicycles", bicycleRoutes);
router.use("/brands", brandRoutes);
router.use("/bicycle-details", bicycleDetailRoutes);
router.use("/customers", customerRoutes);
router.use("/orders", orderRoutes);
export default router;