import { Router } from "express";
import { OrderController } from "./order.controller.js";
const router = Router();
router.get("/", OrderController.getAll);
router.get("/customer/:customerId", OrderController.getByCustomerId);
router.get("/bicycles/price-less-than/:price/weight-greater-than/:weight", OrderController.getByBicyclePriceAndWeight);
router.get("/:id", OrderController.getById);
router.post("/", OrderController.create);
router.put("/:id", OrderController.update);
router.delete("/:id", OrderController.delete);
export default router;
